version: '2'
services:
    festis-app:
        image: festis
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://festis-mysql:3306/festis?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    festis-mysql:
        extends:
            file: mysql.yml
            service: festis-mysql
